<?php

declare(strict_types=1);

return [
    'settings' => [
        'site_tagline' => 'Empowering people through community action, learning, and social impact.',
        'phone' => '+91 9919007190',
        'whatsapp' => '+91 9919007190',
        'email' => 'contact@pradeepsarang.in',
        'address' => 'ग्राम कमरावां, जिला बाराबंकी, उत्तर प्रदेश, भारत',
        'facebook' => '#',
        'instagram' => '#',
        'linkedin' => '#',
        'youtube' => '#',
        'footer_text' => 'Building brighter futures with volunteers, donors, and changemakers.',
    ],
    'sliders' => [
        [
            'title' => '',
            'subtitle' => '',
            'image' => 'assets/images/slider_final_1.png',
        ],
        [
            'title' => '',
            'subtitle' => '',
            'image' => 'assets/images/slider_final_2.png',
        ],
          [
            'title' => '',
            'subtitle' => '',
            'image' => 'assets/images/slider_final_3.webp',
        ],
    ],
    'services' => [
        ['title' => 'सरदार पटेल-अभियान', 'icon' => '/assets/images/sardarpatel.png', 'text' => 'वर्ष पर्यंत संचालित, कार्यक्षेत्र उत्तर प्रदेश प्रदेश'],
        ['title' => 'हरियाली-अभियान', 'icon' => 'fa-solid fa-tree', 'text' => 'वर्ष पर्यंत संचालित, कार्यक्षेत्र सम्पूर्ण भारत'],
        ['title' => 'कपड़ा-बैंक', 'icon' => 'fa-solid fa-person-dress', 'text' => 'शीत काल में संचालित, कार्यक्षेत्र जनपद बाराबंकी'],
        ['title' => 'अवधी-अभियान', 'icon' => 'fa-solid fa-earth-americas', 'text' => 'वर्ष पर्यंत संचालित, कार्यक्षेत्र अवधी बोली क्षेत्र'],
        ['title' => 'परिंदा-संरक्षण', 'icon' => 'fa-solid fa-dove', 'text' => 'ग्रीष्म काल में संचालित, कार्यक्षेत्र जनपद बाराबंकी'],
    ],
    'causes' => [
        ['id' => 1, 'title' => 'सरदार पटेल अभियान', 'slug' => 'sardar-patel-campaign', 'goal' => 150000, 'raised' => 98000, 'image' => 'https://picsum.photos/seed/cause-one/900/700', 'excerpt' => 'राष्ट्रीय एकता और अखंडता के संदेश को जन-जन तक पहुँचाने हेतु यह अभियान संचालित है। इसके माध्यम से युवाओं को देशभक्ति और सामाजिक एकता के प्रति प्रेरित किया जाता है।'],

        ['id' => 2, 'title' => 'अवधी-अभियान', 'slug' => 'language-and-literature-promotion-campaign', 'goal' => 120000, 'raised' => 76000, 'image' => 'https://picsum.photos/seed/cause-two/900/700', 'excerpt' => 'हिंदी एवं अवधी भाषा, साहित्य और संस्कृति के संरक्षण एवं प्रचार-प्रसार के लिए यह अभियान कार्यरत । साहित्यिक गतिविधियों के माध्यम से सांस्कृतिक धरोहर को जीवित रखा जा रहा है।'],

        ['id' => 3, 'title' => 'कपड़ा-बैंक ', 'slug' => 'rural-skills-lab', 'goal' => 200000, 'raised' => 133000, 'image' => 'https://picsum.photos/seed/cause-three/900/700', 'excerpt' => 'प्रदीप सारंग द्वारा संचालित “कपड़ा बैंक” अभियान समाज सेवा का एक अत्यंत मानवीय और सराहनीय प्रयास है। इस अभियान के अंतर्गत जरूरतमंद एवं आर्थिक रूप से ... '],

        ['id' => 4, 'title' => 'हरियाली-अभियान', 'slug' => 'nutrition-for-every-child', 'goal' => 120000, 'raised' => 76000, 'image' => 'https://picsum.photos/seed/cause-two/900/700', 'excerpt' => 'प्रकृति संरक्षण, वृक्षारोपण एवं जल-संरक्षण को बढ़ावा देने के लिए यह अभियान चलाया जाता है। लोगों को पर्यावरण के प्रति जागरूक कर स्वच्छ और हरित समाज बनाने का प्रयास ...'],


        ['id' => 5, 'title' => ' परिंदा-संरक्षण ', 'slug' => 'rural-skills-lab', 'goal' => 200000, 'raised' => 133000, 'image' => 'https://picsum.photos/seed/cause-five/900/700', 'excerpt' => 'प्रदीप सारंग द्वारा संचालित “परिंदा संरक्षण अभियान” प्रकृति और पक्षियों की रक्षा हेतु एक संवेदनशील पहल है। इस अभियान का उद्देश्य बढ़ती गर्मी, जल की कमी और पर्यावरणीय ...'],
    ],
    'events' => [
        ['id' => 1, 'title' => 'Youth Leadership Summit', 'slug' => 'youth-leadership-summit', 'date' => '2026-05-11', 'location' => 'Delhi', 'status' => 'upcoming', 'image' => 'https://picsum.photos/seed/event-one/900/700', 'excerpt' => 'A full-day summit on civic leadership, innovation, and collaboration.'],
        ['id' => 2, 'title' => 'Community Health Camp', 'slug' => 'community-health-camp', 'date' => '2026-04-05', 'location' => 'Lucknow', 'status' => 'past', 'image' => 'https://picsum.photos/seed/event-two/900/700', 'excerpt' => 'Medical screening, consultations, and wellness awareness sessions.'],
        ['id' => 3, 'title' => 'Volunteer Orientation Day', 'slug' => 'volunteer-orientation-day', 'date' => '2026-06-18', 'location' => 'Jaipur', 'status' => 'upcoming', 'image' => '
https://picsum.photos/seed/event-three/900/700', 'excerpt' => 'An interactive orientation for new volunteers to learn about our work and impact.'],
    ],
    'blogs' => [
        ['id' => 1, 'title' => 'How volunteer-led programs reshape local trust', 'slug' => 'how-volunteer-led-programs-reshape-local-trust', 'category' => 'Insights', 'author' => 'Admin', 'date' => '2026-04-14', 'image' => 'https://picsum.photos/seed/blog-one/1200/800', 'excerpt' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent semper sem id pharetra faucibus.', 'content' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vulputate, velit quis rhoncus venenatis, lorem sem volutpat nisi, in faucibus quam leo a urna.</p><p>Curabitur et sapien nec erat feugiat luctus. Donec sit amet nibh sit amet quam lacinia finibus. Nunc rhoncus tortor ut mauris gravida, in facilisis purus cursus.</p>'],
        ['id' => 2, 'title' => 'Field notes from our nutrition campaign', 'slug' => 'field-notes-from-our-nutrition-campaign', 'category' => 'News', 'author' => 'Admin', 'date' => '2026-04-02', 'image' => 'https://picsum.photos/seed/blog-two/1200/800', 'excerpt' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.', 'content' => '<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p><p>Nam a cursus velit. Integer pharetra fermentum justo, et consequat arcu commodo ac.</p>'],
        ['id' => 3, 'title' => '5 ways CSR partners can create longer-term impact', 'slug' => '5-ways-csr-partners-can-create-longer-term-impact', 'category' => 'Strategy', 'author' => 'Admin', 'date' => '2026-03-25', 'image' => 'https://picsum.photos/seed/blog-three/1200/800', 'excerpt' => 'Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.', 'content' => '<p>Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.</p><p>Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam.</p>'],
    ],
    'testimonials' => [
        ['name' => 'Neha Sharma', 'role' => 'Volunteer', 'quote' => 'The platform feels professional and the programs feel human. It helped me move from interest to real contribution.'],
        ['name' => 'Arjun Mehta', 'role' => 'Donor Partner', 'quote' => 'Clear reporting, strong storytelling, and a convincing portfolio of community-led work.'],
    ],
    'team' => [
        ['name' => 'Aarav Singh', 'role' => 'Founder', 'image' => 'https://picsum.photos/seed/team-one/600/600'],
        ['name' => 'Priya Verma', 'role' => 'Programs Lead', 'image' => 'https://picsum.photos/seed/team-two/600/600'],
        ['name' => 'Rahul Das', 'role' => 'Community Coordinator', 'image' => 'https://picsum.photos/seed/team-three/600/600'],
    ],
    'stats' => [
        ['label' => 'Lives Reached', 'value' => '12K+'],
        ['label' => 'Volunteers', 'value' => '480'],
        ['label' => 'Campaigns', 'value' => '36'],
        ['label' => 'Cities', 'value' => '18'],
    ],
    'timeline' => [
        ['id' => 1, 'entry_type' => 'yatra', 'category' => 'yatra', 'year' => '2026', 'title' => 'चार दशकों का अविरल सेवा महोत्सव', 'description' => '1987 से आरंभ हुई निःस्वार्थ जनसेवा यात्रा आज 39वें वर्ष में प्रवेश कर चुकी है। 50,000+ वृक्षों का संरक्षण, 10,000+ मिट्टी के पक्षी जल-सकोरे एवं अवधी साहित्य की अनवरत रचनाशीलता जारी है।', 'sort_order' => 1],
        ['id' => 2, 'entry_type' => 'award', 'category' => 'national', 'year' => '2025', 'title' => 'गंगा साहित्य रत्न व समाज गौरव सम्मान', 'description' => 'लोक-कल्याणकारी पत्रकारिता, पर्यावरण संवर्धन तथा अवधी लोक-साहित्य के संरक्षण हेतु राष्ट्रीय स्तर के सामाजिक मंच द्वारा सर्वसम्मति से अलंकृत।', 'sort_order' => 2],
        ['id' => 3, 'entry_type' => 'award', 'category' => 'literary', 'year' => '2024', 'title' => 'अटल प्रतिभा एवं अवध ज्योति सृजन सम्मान', 'description' => 'उत्तर प्रदेश हिंदी संस्थान सहयोगी मंच द्वारा \'अटल प्रतिभा सम्मान\' तथा अवधी संस्मरण संकलन \'झरिहख\' हेतु विशेष सारस्वत सम्मान।', 'sort_order' => 3],
        ['id' => 4, 'entry_type' => 'award', 'category' => 'national', 'year' => '2023', 'title' => 'राष्ट्रीय आदिवासी गौरव एवं अल्लामा इकबाल अवार्ड', 'description' => 'वंचित व वनवासी समुदायों के सांस्कृतिक संरक्षण हेतु \'राष्ट्रीय आदिवासी गौरव सम्मान\' एवं भाषा उत्सव में प्रतिष्ठित \'अल्लामा इकबाल अवार्ड\'।', 'sort_order' => 4],
        ['id' => 5, 'entry_type' => 'award', 'category' => 'literary', 'year' => '2022', 'title' => 'जनकवि बंशीधर शुक्ल व गोस्वामी तुलसीदास सम्मान', 'description' => '\'प्रकृति साहित्य रत्न\', सुप्रसिद्ध \'जनकवि बंशीधर शुक्ल पुरस्कार\' एवं अवधी भाषा की दीर्घकालिक सेवा हेतु प्रतिष्ठित \'गोस्वामी तुलसीदास सम्मान\' से विभूषित।', 'sort_order' => 5],
        ['id' => 6, 'entry_type' => 'yatra', 'category' => 'social', 'year' => '2020', 'title' => 'कोरोना योद्धा विशिष्ट जनसेवा अभियान', 'description' => 'कोविड-19 संकट के दौरान अग्रिम मोर्चे पर रहकर ग्रामीण असहायों को भोजन, दवा, मास्क वितरण एवं आपातकालीन जीवनरक्षक सुविधाएं पहुँचाईं।', 'sort_order' => 6],
        ['id' => 7, 'entry_type' => 'yatra', 'category' => 'environment', 'year' => '2019', 'title' => '\'ग्रीन गैंग\' की स्थापना एवं \'ग्रीन मॉर्निंग\' का प्रदुर्भाव', 'description' => 'पर्यावरण संरक्षण हेतु \'ग्रीन गैंग\' का गठन। अभिवादन में \'गुड मॉर्निंग\' की जगह \'ग्रीन मॉर्निंग\' (Green Morning) बोलने का अभिनव संस्कार अवध के चौपालों में रोपा।', 'sort_order' => 7],
        ['id' => 8, 'entry_type' => 'award', 'category' => 'social', 'year' => '2018', 'title' => 'सेवा रत्न एवं अवध ज्योति रजत जयंती समारोह', 'description' => 'महिला एवं बाल कल्याण हेतु \'सेवा रत्न सम्मान\' तथा अवधी साहित्य में अनवरत योगदान हेतु अवध ज्योति पत्रिका के रजत जयंती समारोह में सम्मान।', 'sort_order' => 8],
        ['id' => 9, 'entry_type' => 'award', 'category' => 'environment', 'year' => '2016', 'title' => 'वन्य जीव व परिंदा संरक्षण सम्मान (वन मंत्री, उ.प्र.)', 'description' => 'उत्तर प्रदेश शासन के तत्कालीन माननीय वन मंत्री द्वारा पर्यावरण, पक्षी संरक्षण और 10,000+ सकोरा अभियानों के लिए राज्य स्तरीय प्रशस्ति पत्र।', 'sort_order' => 9],
        ['id' => 10, 'entry_type' => 'award', 'category' => 'social', 'year' => '2015', 'title' => 'रेडक्रॉस सोसाइटी एवं जिला प्रशासन सम्मान', 'description' => 'रेडक्रॉस सोसाइटी तथा जिला प्रशासन एवं पुलिस उपाधीक्षक द्वारा सामाजिक सेवा शिविरों के सफल संचालन हेतु विशेष सम्मान पत्र।', 'sort_order' => 10],
        ['id' => 11, 'entry_type' => 'yatra', 'category' => 'social', 'year' => '2010', 'title' => 'नियमित रक्तदान शिविर एवं सार्वजनिक नागरिक अभिनंदन', 'description' => 'सैकड़ों रक्तदान शिविरों के संचालन, आपातकालीन रक्त व्यवस्था एवं विश्वकर्मा जयंती पर जनपदवासियों द्वारा सार्वजनिक नागरिक अभिनंदन।', 'sort_order' => 11],
        ['id' => 12, 'entry_type' => 'award', 'category' => 'national', 'year' => '1997', 'title' => 'आयुर्वेद रत्न उपाधि विभूषण', 'description' => 'पारंपरिक भारतीय चिकित्सा पद्धति, वानस्पतिक जड़ी-बूटियों एवं लोक-स्वास्थ्य के गहन अध्ययन हेतु \'आयुर्वेद रत्न\' की प्रतिष्ठित उपाधि से विभूषित।', 'sort_order' => 12],
        ['id' => 13, 'entry_type' => 'award', 'category' => 'national', 'year' => '1992', 'title' => 'नेहरू युवा केन्द्र (NYK) जिला युवा पुरस्कार', 'description' => 'नेहरू युवा केन्द्र भारत सरकार द्वारा जनपद स्तर पर युवा जागरण, खेलकूद एवं ग्रामीण समाजसेवा में सर्वोत्कृष्ट कार्य के लिए प्रतिष्ठित पुरस्कार।', 'sort_order' => 13],
        ['id' => 14, 'entry_type' => 'award', 'category' => 'national', 'year' => '1991', 'title' => 'महामहिम राज्यपाल द्वारा स्वामी विवेकानंद युवा पुरस्कार', 'description' => 'युवाओं के सर्वांगीण विकास एवं सामाजिक सेवा में अप्रतिम योगदान हेतु तत्कालीन महामहिम राज्यपाल, उत्तर प्रदेश के कर-कमलों द्वारा राजभवन में सम्मानित।', 'sort_order' => 14],
        ['id' => 15, 'entry_type' => 'yatra', 'category' => 'yatra', 'year' => '1988', 'title' => 'गणतंत्र दिवस राष्ट्रीय परेड (NSS नई दिल्ली शिविर)', 'description' => 'ऐतिहासिक क्षण: नई दिल्ली में इंडिया गेट पर 26 जनवरी गणतंत्र दिवस राष्ट्रीय परेड में उत्तर प्रदेश NSS दल के प्रतिनिधि के रूप में ऐतिहासिक मार्च-पास्ट।', 'sort_order' => 15],
        ['id' => 16, 'entry_type' => 'yatra', 'category' => 'yatra', 'year' => '1987', 'title' => 'राष्ट्रीय सेवा योजना (NSS) व युवक मंगल दल से प्रथम संकल्प', 'description' => '1987 में राष्ट्रीय सेवा योजना (NSS) के नैतिक संस्कारों एवं स्वामी विवेकानंद के दर्शन से प्रेरित होकर लोक-सेवा का प्रथम दीप प्रज्वलित किया।', 'sort_order' => 16],
    ],
    'authors' => [
        [
            'id' => 1,
            'name' => 'प्रदीप सारंग (Pradeep Sarang)',
            'role' => 'writer',
            'role_title' => 'संस्थापक एवं प्रधान संपादक',
            'biography' => 'पर्यावरणविद्, लोकसेवक एवं अवधी साहित्यकार। पिछले 39 वर्षों से अवध अंचल में प्रकृति संरक्षण, ग्रीन गैंग अभियान, परिंदा जल-सकोरा एवं अवधी साहित्य के संवर्धन में निरन्तर रत।',
            'profile_photo' => 'assets/images/slider_final_1.png',
            'tags' => ['अवधी लोक-साहित्य', 'पर्यावरण संरक्षण', 'ग्रीन गैंग'],
            'articles_count' => 48,
            'email' => 'contact@pradeepsarang.in',
            'facebook_link' => '#',
            'twitter_link' => '#',
            'linkedin_link' => '#'
        ],
        [
            'id' => 2,
            'name' => 'डॉ. रामेन्द्र नाथ वर्मा',
            'role' => 'advisor',
            'role_title' => 'वरिष्ठ अवधी साहित्यकार व मार्गदर्शक',
            'biography' => 'अवधी बोली व साहित्य के मूर्धन्य विद्वान। अवध की सांस्कृतिक धरोहर, लोकगीतों व ग्रामीण चेतना पर अनेक पुस्तकों व शोध-आलेखों के रचयिता।',
            'profile_photo' => 'https://picsum.photos/seed/author-vitar/400/400',
            'tags' => ['अवधी लोक-साहित्य', 'सांस्कृतिक विरासत', 'शोध-आलेख'],
            'articles_count' => 24,
            'email' => 'ramendra.verma@example.org',
            'facebook_link' => '#',
            'twitter_link' => '#',
            'linkedin_link' => '#'
        ],
        [
            'id' => 3,
            'name' => 'सुनीता द्विवेदी',
            'role' => 'writer',
            'role_title' => 'पर्यावरण व हरित क्रांति विश्लेषक',
            'biography' => 'पर्यावरण संरक्षण, जल-संरक्षण और प्लास्टिक-मुक्त अभियान पर नियमित स्तंभकार। ग्रामीण भारत में महिलाओं की सहभागिता पर विशेष शोध।',
            'profile_photo' => 'https://picsum.photos/seed/author-sunita/400/400',
            'tags' => ['पर्यावरण क्रांति', 'जल संवर्धन', 'जन-जागरण'],
            'articles_count' => 19,
            'email' => 'sunita.d@example.org',
            'facebook_link' => '#',
            'twitter_link' => '#',
            'linkedin_link' => '#'
        ],
        [
            'id' => 4,
            'name' => 'प्रो. आनंद कुमार',
            'role' => 'advisor',
            'role_title' => 'भाषा एवं संस्कृति विशेषज्ञ',
            'biography' => 'विश्वविद्यालय के पूर्व विभागाध्यक्ष। अवधी व हिंदी भाषा के विकास, लोक-भाषा संवर्धन एवं सामाजिक बदलाव पर दर्जनों राष्ट्रीय पत्रिकाओं में रचनाएं।',
            'profile_photo' => 'https://picsum.photos/seed/author-anand/400/400',
            'tags' => ['भाषा व संस्कृति', 'लोक-भाषा', 'मार्गदर्शन'],
            'articles_count' => 31,
            'email' => 'anand.kumar@example.org',
            'facebook_link' => '#',
            'twitter_link' => '#',
            'linkedin_link' => '#'
        ],
        [
            'id' => 5,
            'name' => 'रामेश्वर प्रसाद तिवारी',
            'role' => 'social',
            'role_title' => 'समाजसेवी व लोक-संस्कृति शोधकर्ता',
            'biography' => 'बाराबंकी के ग्रामीण चौपालों में लोक-संस्कृति और परम्परागत जलस्रोतों के पुनरुद्धार हेतु समर्पित कार्यकर्ता व लेखक।',
            'profile_photo' => 'https://picsum.photos/seed/author-rameshwar/400/400',
            'tags' => ['जल संरक्षण', 'ग्रामीण चौपाल', 'लोक-संस्कृति'],
            'articles_count' => 15,
            'email' => 'tiwari.rp@example.org',
            'facebook_link' => '#',
            'twitter_link' => '#',
            'linkedin_link' => '#'
        ],
        [
            'id' => 6,
            'name' => 'कविता शुक्ला',
            'role' => 'social',
            'role_title' => 'सामाजिक कल्याण व बाल अधिकार लेखिका',
            'biography' => 'महिला सशक्तीकरण, कपड़ा-बैंक अभियान व बाल शिक्षा पर निरन्तर लिखने वाली संवेदनशील सामाजिक विचारिका।',
            'profile_photo' => 'https://picsum.photos/seed/author-kavita/400/400',
            'tags' => ['बाल अधिकार', 'महिला कल्याण', 'कपड़ा बैंक'],
            'articles_count' => 22,
            'email' => 'kavita.shukla@example.org',
            'facebook_link' => '#',
            'twitter_link' => '#',
            'linkedin_link' => '#'
        ],
        [
            'id' => 7,
            'name' => 'डॉ. आलोक कुमार सिंह',
            'role' => 'writer',
            'role_title' => 'पर्यावरण वैज्ञानिक व हरित स्तम्भ',
            'biography' => 'वृक्षारोपण, पक्षी संरक्षण अभियान एवं मृदा स्वास्थ्य पर वैज्ञानिक दृष्टिकोण से प्रकाश डालने वाले स्तंभकार।',
            'profile_photo' => 'https://picsum.photos/seed/author-alok/400/400',
            'tags' => ['हरित क्रांति', 'पक्षी संरक्षण', 'पर्यावरण विज्ञान'],
            'articles_count' => 18,
            'email' => 'alok.singh@example.org',
            'facebook_link' => '#',
            'twitter_link' => '#',
            'linkedin_link' => '#'
        ],
        [
            'id' => 8,
            'name' => 'राजेश वर्मा',
            'role' => 'guest',
            'role_title' => 'ग्रामीण पत्रकारिता व लोक-समाचार',
            'biography' => 'ग्रामीण जीवन की चुनौतियों और जमीनी जन-हितकारी अभियानों की रिपोर्टिंग करने वाले वरिष्ठ पत्रकार व स्तम्भकार।',
            'profile_photo' => 'https://picsum.photos/seed/author-rajesh/400/400',
            'tags' => ['ग्रामीण पत्रकारिता', 'लोक-समाचार', 'जन-आवाज'],
            'articles_count' => 14,
            'email' => 'rajesh.v@example.org',
            'facebook_link' => '#',
            'twitter_link' => '#',
            'linkedin_link' => '#'
        ],
        [
            'id' => 9,
            'name' => 'नेहा शर्मा',
            'role' => 'guest',
            'role_title' => 'युवा चेतना व स्वयंसेवक संवाद',
            'biography' => 'युवाओं को सामाजिक सरोकारों और राष्ट्रीय सेवा योजना से जोड़ने के विषय पर लिखने वाली युवा लेखिका।',
            'profile_photo' => 'https://picsum.photos/seed/author-neha/400/400',
            'tags' => ['युवा चेतना', 'स्वयंसेवक', 'डिजिटल संवाद'],
            'articles_count' => 11,
            'email' => 'neha.sharma@example.org',
            'facebook_link' => '#',
            'twitter_link' => '#',
            'linkedin_link' => '#'
        ],
    ],
];
